#!/usr/bin/python3

import dbus
import sys

# Check if two command line arguments were provided
if len(sys.argv) != 3:
    print("Usage: create_sms <modem_name> <phone_number>")
    sys.exit(1)

bus = dbus.SystemBus()

modem_path = sys.argv[1]
number = sys.argv[2]
message = sys.stdin.read()

modem_manager = bus.get_object('org.freedesktop.ModemManager1', '/org/freedesktop/ModemManager1')
modem = bus.get_object('org.freedesktop.ModemManager1', modem_path)
messaging = dbus.Interface(modem, "org.freedesktop.ModemManager1.Modem.Messaging")
msg = dbus.Dictionary(
	{
		dbus.String('number') : dbus.String(number),
		dbus.String('text') : dbus.String(message)
	},
	signature=dbus.Signature('sv'))

result = messaging.Create(msg)

print(str(result))


